contributors.txt
Adding my name and email to the contributors.txt
=> Added Blake Gilmore information to contributors document

contributors.txt
Added my name to the contributors
=> Contributors names

contributors.txt
=> Cade add pt 2

repo_mining/Johnson_authorsFileTouches.py, repo_mining/Johnson_scatterplot.py
=> Added Johnson's scripts

repo_mining/Warren-Salazar_CollectFiles.py, repo_mining/Warren_authorsFileTouches.py, repo_mining/Warren_scatterplot.py
=> Warren Salazar - Scripts

cadeAihara_chatGPT/cadeAihara_ORIGINALas3.cpp, cadeAihara_chatGPT/cadeAihara_REFACTOREDas3.cpp
2
Finished adding orignal and refactored code of code block
=> task 2.1 refactored code

chatgpt/Cade_Aihara/cadeAihara_complexCode2_3.cpp
finished 2.3 and broke down complex code to be more digestable to reader
=> push of assignment 2.3

chatgpt/Cade_Aihara/cadeAihara_ymlTest2_4.yml
=> push of assignment 2.4 test yml file

chatgpt/Warren_Salazar/Warren_Salazar_task2_1.cpp
Provides the code snippet that needs to be addressed by #64
=> Task 2.1 Code Snippet

chatgpt/Warren_Salazar/Warren_Salazar_task2_2.cpp
Provides the code snippet that needs to be addressed by #66
=> Task 2.2 Code Snippet

chatgpt/wordladder.cpp
https://chat.openai.com/share/8c00b422-463b-4cfb-91ad-db7b45936dbc
This documentation provides clear explanations of each function's purpose, input parameters, return values, and any additional information necessary for understanding and using the code effectively. - Mr. ChatGPT
=> Added documentation Task 2.2

chatgpt/Justin_Llamas/Justin_Llamas_task2_1.cpp
Old CS135 lab, using this to be refactored since this was when I first started coding.
=> Adding program that needs to be refactored

chatgpt/Justin_Llamas/Justin_Llamas_task2_1.cpp
- Removed unnecessary constants and variables
- Used a vector instead of an array to store data, to avoid magic numbers
- Simplified error calculations and output
- Streamlined loops for finding minimum and maximum values
- Improved code formatting and comments for readability.
=> Incorportaing ChatGPT suggestions

chatgpt/Xiaojun_Ruan/XiaojunRuan_Task2_1.cpp
This is referencing to Issue #79 
What needs to be refactored:
Calculations for area
calculations for perimeter
calculations for Volume
Printing
=> Xiaojun Ruan Chatgpt Task2.1 before refactoring Updated

chatgpt/Justin_Llamas/Justin_Llamas_task2_2.cpp
Comments are messy, and could be a lot cleaner and simpler so others can comprehend the code better.
=> Task 2.2 Code

chatgpt/Justin_Llamas/Justin_Llamas_task2_3.c
There is a lot going on in this piece of code, lets see how ChatGPT will handle this.
=> Complex Code for 12 days of Christmas

chatgpt/Johnson_Nguyen/JohnsonNguyen_Task_2_2.py
This code needs better documentation Issue #93.
=> Code needing documentation

chatgpt/Xiaojun_Ruan/XiaojunRuan_Task2_3.cpp
This code is referencing to issue #94 
Task:
Need to change the complex code into simplified version for the calculation and printing function.
=> Xiaojun Ruan Task 2.3 Code Complexity

chatgpt/Alvaro_Hernandez/LL.h
Added an LL.h file within chatgpt/Alvaro_Hernandez which is the code snippet that is in need of documentation that is referenced in issue this resolves #99
=> Added the code snippet that is in need of documentation

chatgpt/Alvaro_Hernandez/Ocean_Treasure.py
This is a short yet not so simple game that I and others may need assistance in understanding on how it works as well as how it's so compact, may be in need or refactoring.
=> Added python game that is in need of explaining and possibly refactoring
